[package]
name = "pie_audit_log"
version = "0.1.0"
edition = "2021"

[dependencies]
pie_common = { path = "../common" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
