[package]
name = "pie_episodes"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
uuid = { version = "1", features = ["v4", "serde"] }

pie_common = { path = "../common" }

[dev-dependencies]
tempfile = "3"