[package]
name = "operator_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
pie_common = { path = "../common" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ratatui = "0.26"
crossterm = "0.27"
libc = "0.2"