[package]
name = "pieBot_audit_spec"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["serde", "v4"] }
pieBot_common = { path = "../common" }
